---
- hosts: localhost

  vars_files:
    - my_vars.yml

  tasks:
  - name: Do my sudo tasks
    become: true
    become_method: sudo
    become_user: root
    block:
      - name: Install my favourite packages
        apt:
          name: "{{ item }}"
          update_cache: yes
          state: latest
        with_items: "{{ my_apt_packages }}"

      - name: Install my favourite classic snap packages
        shell: snap install {{ item }} --classic
        args:
          creates: /var/lib/snapd/snaps/{{ item }}*.snap
        with_items: "{{ my_classic_snap_packages }}"

  - name: Install my favourite python packages (via pip)
    pip:
      name: "{{ item }}"
      extra_args: --user
    with_items: "{{ my_python_packages }}"

  - name: Install my favourite atom packages
    shell: apm install {{ item }}
    args:
      creates: /home/{{ lookup('env','SUDO_USER') }}/.atom/packages/{{ item }}
    with_items: "{{ my_atom_packages }}"

  - name: Install my favourite npm packages (globally)
    npm:
      name: "{{ item }}"
      global: yes
    with_items: "{{ my_global_npm_packages }}"

  - name: Setup my git configuration
    git_config:
      name: "{{ item.name }}"
      scope: global
      value: "{{ item.value }}"
    with_items: "{{ my_git_configuration }}"
