---
- hosts: localhost

  vars_files:
    - my_vars.yml

  tasks:
  - name: Do sudo tasks
    become: true
    become_method: sudo
    become_user: root
    block:
      - name: Install my favourite packages
        apt:
          name: "{{ item }}"
          update_cache: yes
          state: latest
        with_items: "{{ my_apt_packages }}"

  - name: Install my favourite atom packages
    shell: apm install {{ item }}
    args:
      creates: /home/{{ lookup('env','SUDO_USER') }}/.atom/packages/{{ item }}
    with_items: "{{ my_atom_packages }}"

  - name: Install my favourite npm packages (globally)
    npm:
      name: "{{ item }}"
      global: yes
    with_items: "{{ my_global_npm_packages }}"
